/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emoti;

import damic.ui.MainWindow;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author aariasgonzalez
 */
public class EmotiPanel extends javax.swing.JPanel {

    /**
     * Creates new form EmotiPanel
     */
    public EmotiPanel() {
        initComponents();
        setLayout(new FlowLayout());
        this.setPreferredSize(new Dimension(210, 150));
        
        for(int i=0;i<Emoti.LIST.length;i++){
            final JLabel lab = new JLabel();
            lab.setSize(16, 16);
            lab.setToolTipText(Emoti.LIST[i].toLowerCase());
            lab.setIcon(Emoti.get(Emoti.LIST[i].toLowerCase()));
            lab.addMouseListener(new MouseAdapter(){  
                public void mouseClicked(MouseEvent e){  
                    MainWindow.getInstance().appendLocalMessage(Emoti.replace(lab.getToolTipText()));
                }  
            }); 
            lab.getToolTipText();
            add("c"+i, lab);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
